# Generated by Django 5.1.6 on 2025-02-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_nft_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='title',
            field=models.TextField(default='a title'),
            preserve_default=False,
        ),
    ]
