# Generated by Django 5.1.6 on 2025-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_nft_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
