# Generated by Django 5.1.6 on 2025-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_nft_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
