# Generated by Django 5.1.6 on 2025-02-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_nft_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='A category description'),
            preserve_default=False,
        ),
    ]
