# Generated by Django 5.1.6 on 2025-02-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=30),
            preserve_default=False,
        ),
    ]
