# Generated by Django 5.1.6 on 2025-02-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
