# Generated by Django 5.1.6 on 2025-02-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_nft_is_admin_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={'ordering': ['-created_at']},
        ),
    ]
