# Generated by Django 5.1.6 on 2025-02-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_is_active_useraccount_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
