# Generated by Django 5.1.6 on 2025-02-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover-images/'),
        ),
    ]
