# Generated by Django 5.1.6 on 2025-02-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='sales_balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=30),
        ),
    ]
