# Generated by Django 5.1.6 on 2025-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='transaction_hash',
            field=models.TextField(default='hak'),
            preserve_default=False,
        ),
    ]
