# Generated by Django 5.1.6 on 2025-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.TextField(default='hak'),
            preserve_default=False,
        ),
    ]
