# Generated by Django 5.1.6 on 2025-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_deposit_transaction_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='initial_admin_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='initial_admin_activity',
            field=models.BooleanField(default=False),
        ),
    ]
