# Generated by Django 5.1.6 on 2025-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('minting_fee', models.DecimalField(decimal_places=4, max_digits=30)),
                ('deposit_address', models.TextField()),
            ],
        ),
    ]
